
package view;
import model.Report;
import model.SupplierHistory;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import database.SupplierDB;

public class SupplierHistoryGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SupplierHistoryGUI.class.getName());

    public SupplierHistoryGUI() {

    initComponents();

    loadHistoryTable();
}

    public void loadHistoryTable() {

    try {

        Connection conn =
                new SupplierDB().connectDB();

        String sql =
                "SELECT * FROM supplier_history";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        DefaultTableModel model =
                (DefaultTableModel)
                tblSupplierHistory.getModel();

        model.setRowCount(0);

        while(rs.next()) {

           model.addRow(new Object[]{

rs.getString("supplier_name"),
rs.getString("book_title"),
rs.getInt("quantity"),
rs.getString("action_description"),
rs.getString("action_date")


});

        }

        conn.close();

    } catch(Exception e) {

        e.printStackTrace();
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchSupplierID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierHistory = new javax.swing.JTable();
        btnViewHistory = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Supplier Name :");

        txtSearchSupplierID.addActionListener(this::txtSearchSupplierIDActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tblSupplierHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier Name", "Book Title", "Quantity", "Action", "Action Date"
            }
        ));
        jScrollPane1.setViewportView(tblSupplierHistory);

        btnViewHistory.setText("View History");
        btnViewHistory.addActionListener(this::btnViewHistoryActionPerformed);

        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(this::btnGenerateReportActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("BOOKSTORE INVENTORY & SALES MANAGEMENT SYSTEM");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("VIEW SUPPLIER HISTORY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnViewHistory)
                                .addGap(45, 45, 45)
                                .addComponent(btnGenerateReport)
                                .addGap(68, 68, 68)
                                .addComponent(btnBack)
                                .addGap(50, 50, 50))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnSearch))
                            .addComponent(jLabel7))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearchSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateReport)
                    .addComponent(btnBack)
                    .addComponent(btnViewHistory))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        try {

    Connection conn =
            new SupplierDB().connectDB();

    String sql =
            "SELECT COUNT(*) AS total FROM supplier_history";

    PreparedStatement pst =
            conn.prepareStatement(sql);

    ResultSet rs =
            pst.executeQuery();

    if(rs.next()) {

        int total =
                rs.getInt("total");

        JOptionPane.showMessageDialog(
                this,
                "Supplier Report Generated!\n"
                + "Total History Records: "
                + total
        );
    }

    conn.close();

} catch(Exception e) {

    e.printStackTrace();
}
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnViewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHistoryActionPerformed
            loadHistoryTable();
    }//GEN-LAST:event_btnViewHistoryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     String keyword =
        txtSearchSupplierID.getText();

try {

    Connection conn =
            new SupplierDB().connectDB();

    String sql =
"SELECT * FROM supplier_history WHERE supplier_name LIKE ?";

    PreparedStatement pst =
            conn.prepareStatement(sql);

    pst.setString(1,
            "%" + keyword + "%");

    ResultSet rs =
            pst.executeQuery();

    DefaultTableModel model =
            (DefaultTableModel)
            tblSupplierHistory.getModel();

    model.setRowCount(0);

    while(rs.next()) {

        model.addRow(new Object[]{


rs.getString("supplier_name"),
rs.getString("book_title"),
rs.getInt("quantity"),
rs.getString("action_description"),
rs.getString("action_date")


});

    }

    conn.close();

} catch(Exception e) {

    e.printStackTrace();
} 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSupplierIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SupplierHistoryGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplierHistory;
    private javax.swing.JTextField txtSearchSupplierID;
    // End of variables declaration//GEN-END:variables
}
