/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package SalesModule;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class CartGUI extends javax.swing.JFrame {
    
private static DefaultTableModel sharedCartModel;    

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(CartGUI.class.getName());

    private String productID;
    private String title;
    private double price;
    private int quantity;
    private double subtotal;

    public CartGUI() {
        initComponents();
        
      setDefaultCloseOperation( javax.swing.WindowConstants.HIDE_ON_CLOSE );  
    }
    
   public static DefaultTableModel getSharedCartModel() {

    return sharedCartModel;
}

public CartGUI(
String productID,
String title,
double price,
int quantity) {


initComponents();

this.productID = productID;
this.title = title;
this.price = price;
this.quantity = quantity;
this.subtotal = price * quantity;

txtTotalAmount.setEditable(false);

if(sharedCartModel == null) {

    sharedCartModel =
            (DefaultTableModel)
            jTable1.getModel();
}
else {

    jTable1.setModel(sharedCartModel);
}

while(sharedCartModel.getRowCount() > 0 &&
      sharedCartModel.getValueAt(0, 0) == null) {

    sharedCartModel.removeRow(0);
}

sharedCartModel.addRow(new Object[]{

    this.productID,
    this.title,
    this.price,
    this.quantity,
    this.subtotal
});

double total = 0;

for(int i = 0;
        i < sharedCartModel.getRowCount();
        i++) {

    total += Double.parseDouble(
            sharedCartModel
                    .getValueAt(i, 4)
                    .toString()
    );
}

txtTotalAmount.setText(
        String.valueOf(total)
);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        btnRemoveItem = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Produtct ID", "Title", "Price", "Quantity", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cart");

        jLabel2.setText("Total Amount (RM): ");

        txtTotalAmount.setEditable(false);

        btnRemoveItem.setText("Remove Item");
        btnRemoveItem.addActionListener(this::btnRemoveItemActionPerformed);

        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(this::btnCheckoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnRemoveItem)
                        .addGap(66, 66, 66)
                        .addComponent(btnCheckout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveItem)
                    .addComponent(btnCheckout))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        double grandTotal = 0; 
        for(int i = 0; i < sharedCartModel.getRowCount(); 
                i++) { 
            grandTotal += Double.parseDouble( 
                    sharedCartModel .getValueAt(i, 4) .toString() ); }
        Checkout checkout = new Checkout( "Multiple Books", grandTotal, 1, grandTotal ); 
        checkout.setVisible(true); 
       setVisible(false);
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        int selectedRow =
        jTable1.getSelectedRow();

if(selectedRow == -1){

    JOptionPane.showMessageDialog(
            this,
            "Please select item!"
    );

    return;
}

DefaultTableModel model =
        (DefaultTableModel) jTable1.getModel();

model.removeRow(selectedRow);

double total = 0;

for(int i = 0; i < model.getRowCount(); i++) {

    total += Double.parseDouble(
        model.getValueAt(i, 4).toString()
    );
}

txtTotalAmount.setText(String.valueOf(total));
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CartGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
