/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SalesModule;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import bookstore.database.DatabaseManager;
/**
 *
 * @author user
 */
public class PaymentGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentGUI.class.getName());

   private String title;
private double price;
private int quantity;
private double totalAmount;
    public PaymentGUI() {
        initComponents();
    }
  

public PaymentGUI(
        String title,
        double price,
        int quantity,
        double totalAmount) {

    initComponents();

    this.title = title;
    this.price = price;
    this.quantity = quantity;
    this.totalAmount = totalAmount;

    txtAmount.setEditable(false);

    txtAmount.setText(
            String.valueOf(totalAmount)
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbCard = new javax.swing.JRadioButton();
        rbOnlineBanking = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnPayNow = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmBank = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Payment");

        jLabel2.setText("Payment Method");

        paymentGroup.add(rbCard);
        rbCard.setText("Card");
        rbCard.addActionListener(this::rbCardActionPerformed);

        paymentGroup.add(rbOnlineBanking);
        rbOnlineBanking.setText("Online Banking");

        jLabel3.setText("Total Amount (RM): ");

        btnPayNow.setText("Pay Now");
        btnPayNow.addActionListener(this::btnPayNowActionPerformed);

        jLabel4.setText("Card Number");

        txtCardNumber.addActionListener(this::txtCardNumberActionPerformed);

        jLabel5.setText("Bank Name");

        cmBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maybank", "Bank Islam", "Cimb Bank", "BSN", "RHB Bank", "Bank Rakyat" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbCard, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbOnlineBanking, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCardNumber)
                            .addComponent(cmBank, 0, 139, Short.MAX_VALUE)
                            .addComponent(txtAmount)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnPayNow))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOnlineBanking)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnPayNow)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCardActionPerformed

    private void txtCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardNumberActionPerformed

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed
     try {

    Connection conn =
            DatabaseManager.connectDB();

    String paymentMethod = "";

    if(rbCard.isSelected()) {

        paymentMethod = "Card";

    } else if(rbOnlineBanking.isSelected()) {

        paymentMethod = "Online Banking";
    }

    double amount =
            Double.parseDouble(
                    txtAmount.getText()
            );

    String sql =

"INSERT INTO payments(order_id, payment_method, payment_amount, payment_date) VALUES (?, ?, ?, NOW())";

    PreparedStatement pst =
            conn.prepareStatement(sql);

    pst.setInt(1, 1);

    pst.setString(2, paymentMethod);

    pst.setDouble(3, amount);

    pst.executeUpdate();

    // STOCK DEDUCTION

    DefaultTableModel model =
            CartGUI.getSharedCartModel();

    String updateSQL =

"UPDATE product SET stockQty = stockQty - ? WHERE productID = ?";

    PreparedStatement updatePst =
            conn.prepareStatement(updateSQL);

    for(int i = 0; i < model.getRowCount(); i++) {

        int quantity =
                Integer.parseInt(
                        model.getValueAt(i, 3).toString()
                );

        int productID =
                Integer.parseInt(
                        model.getValueAt(i, 0).toString()
                );

        updatePst.setInt(1, quantity);

        updatePst.setInt(2, productID);

        updatePst.executeUpdate();
    }

    JOptionPane.showMessageDialog(
        this,
        "Payment Successful!"
);

InvoiceGUI invoice =
        new InvoiceGUI(
                title,
                price,
                quantity,
                amount,
                "SUCCESSFUL"
        );

invoice.setVisible(true);

model.setRowCount(0);

dispose();

    conn.close();

} catch(Exception e) {

    e.printStackTrace();

    JOptionPane.showMessageDialog(
            this,
            "Payment Failed!"
    );
}
    }//GEN-LAST:event_btnPayNowActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaymentGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayNow;
    private javax.swing.JComboBox<String> cmBank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.ButtonGroup paymentGroup;
    private javax.swing.JRadioButton rbCard;
    private javax.swing.JRadioButton rbOnlineBanking;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCardNumber;
    // End of variables declaration//GEN-END:variables
}
