/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SalesModule;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
/**
 *
 * @author user
 */
public class ProductGUI extends javax.swing.JFrame {
    
    private String selectedProductID;
private String selectedTitle;
private double selectedPrice;
private int selectedQuantity;
private Cart cart = new Cart();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductGUI.class.getName());

    /**
     * Creates new form ProductGUI
     */
    public ProductGUI() {
        initComponents();
       
        
    
         DefaultTableModel model =
        (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);

try {

    Connection conn =
            DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/bookstore_db",
                    "root",
                    ""
            );

    String sql =
            "SELECT * FROM product";

    PreparedStatement pst =
            conn.prepareStatement(sql);

    ResultSet rs =
            pst.executeQuery();

    while(rs.next()) {

        model.addRow(new Object[]{

            rs.getInt("productID"),
            rs.getString("title"),
            rs.getString("author"),
            rs.getDouble("price"),
            rs.getString("isbn"),
            rs.getInt("stockQty")
        });
    }

    conn.close();

} catch(Exception e) {

    e.printStackTrace();
}
    }
public javax.swing.JTable getCartTable() {


return jTable1;

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddtoCart = new javax.swing.JButton();
        btnViewCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Title", "Author", "Price", "ISBN", "Stock"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Book Store");

        jLabel2.setText("Quantity");

        btnAddtoCart.setText("Add To Cart");
        btnAddtoCart.addActionListener(this::btnAddtoCartActionPerformed);

        btnViewCart.setText("View Cart");
        btnViewCart.addActionListener(this::btnViewCartActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnAddtoCart)
                        .addGap(39, 39, 39)
                        .addComponent(btnViewCart)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtoCart)
                    .addComponent(btnViewCart))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCartActionPerformed
     CartGUI cartGUI = new CartGUI( selectedProductID, selectedTitle, selectedPrice, selectedQuantity ); cartGUI.setVisible(true);
    }//GEN-LAST:event_btnViewCartActionPerformed

    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed
      int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a book first!"
        );
        return;
    }

    if (txtQuantity.getText().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please enter quantity!"
        );
        return;
    }

    selectedProductID =
            jTable1.getValueAt(selectedRow, 0).toString();

    selectedTitle =
            jTable1.getValueAt(selectedRow, 1).toString();

    selectedPrice =
            Double.parseDouble(
                    jTable1.getValueAt(selectedRow, 3).toString()
            );

    selectedQuantity =
            Integer.parseInt(txtQuantity.getText());
    int stockQuantity =
        Integer.parseInt(
                jTable1.getValueAt(selectedRow, 5).toString()
        );

if(selectedQuantity > stockQuantity){

    JOptionPane.showMessageDialog(
            this,
            "Insufficient stock!"
    );

    return;
}

    Product product = new Product();

    product.setProductID(selectedProductID);
    product.setTitle(selectedTitle);
    product.setAuthor(
            jTable1.getValueAt(selectedRow, 2).toString()
    );
    product.setPrice(selectedPrice);

    cart.setQuantity(selectedQuantity);

cart.setTotalAmount(
        selectedPrice * selectedQuantity
);

cart.addItem(product);
    JOptionPane.showMessageDialog(
            this,
            "Book Added To Cart\n\n"
            + "Title : " + selectedTitle
            + "\nQuantity : " + selectedQuantity
            + "\nSubtotal : RM"
            + (selectedPrice * selectedQuantity)
    );
    
    new CartGUI(
selectedProductID,
selectedTitle,
selectedPrice,
selectedQuantity
).setVisible(true);

    }//GEN-LAST:event_btnAddtoCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoCart;
    private javax.swing.JButton btnViewCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
