
package ReportingAndAnalytics;

import javax.swing.*;
import java.awt.*;
import java.util.Map;

/**
 * SalesTrendFrame.java
 * GUI for "View Sales Trend Analytics" use case (Sequence Diagram 7).
 * Actor: Manager
 *
 * Flow:
 * 2. (Optional) Select time interval (Daily/Monthly)
 * 3-9. getSalesTrend(interval)
 * 10. Display Sales Trend
 * 9a. Insufficient data -> "Not enough data for trend"
 */
public class SalesTrendAnalytics extends JFrame {
    private AnalyticsController analyticsController;
    private JComboBox<String> intervalBox;
    private LineChartPanel chartPanel;

    public SalesTrendAnalytics(AnalyticsController analyticsController) {
        this.analyticsController = analyticsController;

        setTitle("View Sales Trend Analytics");
        setSize(550, 450);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout(10, 10));

        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        topPanel.add(new JLabel("Time Interval:"));
        intervalBox = new JComboBox<>(new String[]{"Daily", "Monthly"});
        topPanel.add(intervalBox);

        JButton viewBtn = new JButton("View Sales Trend");
        topPanel.add(viewBtn);

        add(topPanel, BorderLayout.NORTH);

        chartPanel = new LineChartPanel();
        chartPanel.setPreferredSize(new Dimension(500, 350));
        add(chartPanel, BorderLayout.CENTER);

        // 1. Select Sales Trend -> 3. getSalesTrend(interval)
        viewBtn.addActionListener(e -> loadTrend());

        loadTrend();
    }

    private void loadTrend() {
        String interval = (String) intervalBox.getSelectedItem();

        // 3-9. getSalesTrend(interval)
        Map<String, Double> trend = analyticsController.getSalesTrend(interval);

        if (trend == null) {
            // 9a. "Not enough data for trend"
            JOptionPane.showMessageDialog(this, "Not enough data for trend",
                    "Insufficient Data", JOptionPane.WARNING_MESSAGE);
            chartPanel.setData(null);
        } else {
            // 10. Display Sales Trend
            chartPanel.setData(trend);
        }
        chartPanel.repaint();
    }

    /**
     * LineChartPanel - simple line chart renderer representing the
     * "trend graph" / "chart" object generated by ChartService.generateLineChart().
     */
    static class LineChartPanel extends JPanel {
        private Map<String, Double> data;

        public void setData(Map<String, Double> data) {
            this.data = data;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (data == null || data.isEmpty()) {
                g.drawString("No data to display", 20, 20);
                return;
            }

            int width = getWidth();
            int height = getHeight();
            int padding = 50;

            double max = data.values().stream().mapToDouble(Double::doubleValue).max().orElse(1);
            int n = data.size();
            int stepX = (width - 2 * padding) / Math.max(1, n - 1);

            Graphics2D g2 = (Graphics2D) g;
            g2.setColor(new Color(34, 139, 34));
            g2.setStroke(new BasicStroke(2));

            int prevX = -1, prevY = -1;
            int i = 0;
            for (Map.Entry<String, Double> entry : data.entrySet()) {
                int x = padding + i * stepX;
                int y = height - padding - (int) ((entry.getValue() / max) * (height - 2 * padding));

                g2.fillOval(x - 3, y - 3, 6, 6);
                if (prevX != -1) {
                    g2.drawLine(prevX, prevY, x, y);
                }

                g2.setColor(Color.BLACK);
                g2.rotate(Math.toRadians(45), x, height - padding + 15);
                g2.drawString(entry.getKey(), x, height - padding + 15);
                g2.rotate(-Math.toRadians(45), x, height - padding + 15);
                g2.setColor(new Color(34, 139, 34));

                prevX = x;
                prevY = y;
                i++;
            }
        }
    }   
}
