
package ReportingAndAnalytics;


import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.util.Map;

/**
 * SalesReport.java
 * GUI for "Generate Sales Report" use case (Sequence Diagram 2).
 * Actor: Manager
 *
 * Flow:
 * 2. Enter date range (from, to)
 * 3-10. generateSalesReport(from, to)
 * 11. Display Sales Report (with charts)
 * 2a. No date selected -> use default (current month)
 * 10a. Database connection failed -> "Unable to retrieve data"
 * 10b. Invalid date format -> show error and request correction
 */
public class SalesReport extends JFrame {
    private ReportController reportController;

    private JTextField fromField;
    private JTextField toField;
    private JLabel summaryLabel;
    private ChartPanel chartPanel;

    public SalesReport(ReportController reportController) {
        this.reportController = reportController;

        setTitle("Generate Sales Report");
        setSize(550, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout(10, 10));

        JPanel topPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(8, 8, 8, 8);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // 2. Enter date range (from, to)
        gbc.gridx = 0; gbc.gridy = 0;
        topPanel.add(new JLabel("From (YYYY-MM-DD):"), gbc);
        gbc.gridx = 1;
        fromField = new JTextField(12);
        topPanel.add(fromField, gbc);
        
      
        gbc.gridx = 0; gbc.gridy = 1;
        topPanel.add(new JLabel("To (YYYY-MM-DD):"), gbc);
        gbc.gridx = 1;
        toField = new JTextField(12);
        topPanel.add(toField, gbc);
        
        LocalDate now = LocalDate.now();

fromField.setText(
        now.withDayOfMonth(1).toString()
);

toField.setText(
        now.toString()
);

        gbc.gridx = 0; gbc.gridy = 2; gbc.gridwidth = 2;
        JButton generateBtn = new JButton("Generate Sales Report");
        topPanel.add(generateBtn, gbc);

        gbc.gridy = 3;
        summaryLabel = new JLabel(" ");
        topPanel.add(summaryLabel, gbc);

        add(topPanel, BorderLayout.NORTH);

        chartPanel = new ChartPanel();
        chartPanel.setPreferredSize(new Dimension(500, 300));
        add(chartPanel, BorderLayout.CENTER);

        // 1. Select "Record Sales" (report option) -> 3. generateSalesReport(from,to)
        generateBtn.addActionListener(e -> {
            String fromText = fromField.getText().trim();
            String toText = toField.getText().trim();

            LocalDate from = null;
            LocalDate to = null;

            try {
                // 2a. If no date selected, use default (current month) - handled in controller
                if (!fromText.isEmpty()) from = LocalDate.parse(fromText);
                if (!toText.isEmpty()) to = LocalDate.parse(toText);
            } catch (Exception ex) {
                // 10b. Invalid date format -> show error message and request correction
                JOptionPane.showMessageDialog(this,
                        "Invalid date format. Please use YYYY-MM-DD.",
                        "Invalid Date Format", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3-10. generateSalesReport(from, to)
            ReportController.SalesReportResult result = reportController.generateSalesReport(from, to);

            if (result == null) {
                // 10a. Database connection failed
                JOptionPane.showMessageDialog(this, "Unable to retrieve data",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 11. Display Sales Report (with charts)
            summaryLabel.setText(String.format(
                    "<html>Period: %s to %s<br>Total Revenue: %.2f<br>Total Transactions: %d</html>",
                    result.from, result.to, result.totalRevenue, result.totalTransactions));

            chartPanel.setData(result.chart);
            chartPanel.repaint();
        });
    }

    /**
     * ChartPanel - simple bar chart renderer representing the
     * "chart" object generated by ChartService.generateChart().
     */
    static class ChartPanel extends JPanel {
        private Map<String, Double> data;

        public void setData(Map<String, Double> data) {
            this.data = data;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (data == null || data.isEmpty()) {
                g.drawString("No data to display", 20, 20);
                return;
            }

            int width = getWidth();
            int height = getHeight();
            int padding = 40;
            int barWidth = Math.max(20, (width - 2 * padding) / data.size());

            double max = data.values().stream().mapToDouble(Double::doubleValue).max().orElse(1);

            int x = padding;
            for (Map.Entry<String, Double> entry : data.entrySet()) {
                int barHeight = (int) ((entry.getValue() / max) * (height - 2 * padding));
                g.setColor(new Color(70, 130, 180));
                g.fillRect(x, height - padding - barHeight, barWidth - 10, barHeight);
                g.setColor(Color.BLACK);
                g.drawString(String.format("%.0f", entry.getValue()), x, height - padding - barHeight - 5);

                // Rotate label for readability
                Graphics2D g2 = (Graphics2D) g;
                g2.rotate(Math.toRadians(45), x, height - padding + 15);
                g2.drawString(truncate(entry.getKey(), 10), x, height - padding + 15);
                g2.rotate(-Math.toRadians(45), x, height - padding + 15);

                x += barWidth;
            }
        }

        private String truncate(String s, int len) {
            return s.length() > len ? s.substring(0, len) + "..." : s;
        }
    }
}    
